### ISSUE TITLE
Задачки

### ISSUE THREAD

**Issue by Ivakhnenkoalex** [Ivakhnenkoalex/DS-C-SHARP#2]
@vdetstvepil 
В задачке B2 была ошибка во второй проверке : Там 10003 выводилось раньше чем 22, что я исправил
В B5 выводу у моей функции, и той что правильно одинаков, но оно все равно не засчитывает

**Comment by vdetstvepil** [comment]
В задаче B2 нет ошибки: строка 10003 выводится раньше, чем 22, потому что идет сравнение строк. Представь словарь, где слова на букву А идут раньше слов на букву Б.

**Comment by vdetstvepil** [comment]
Хорошо, принято.
